Lastpage Review
TapishKhari/FirstDevProject pull request #3
Opened 2022-08-30 16:24 UTC by TapishKhari

Lastpage Review:

1. Updated HTML file for the last page.
2. Added images.
3. added css to complete the last page
4. Linter setup and added it
5. Run checks for HTML and css file.

2022-08-30 16:38 UTC, jasonfelice requested changes
Hi @TapishKhari, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Good commit messages✔️
GitHub flow followed✔️
Descriptive PR✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-30 16:38 UTC, jasonfelice commented on index.html
> +                    <hr class="final_line">
- [ ] **\[OPTIONAL\]** This black bar is not part of the template, it's just there. So, you can consider removing it.
![image](https://user-images.githubusercontent.com/92215878/187491297-7d30d6c4-0581-41e0-bc8c-3a79cf39de75.png)

2022-08-30 16:38 UTC, jasonfelice commented on index.html
> +                <form action="/action_page.php" class="form_div">
- [ ] Kindly make sure you are using [Formspree service](https://formspree.io/html) to collect the data. Please sign up and use that link.

2022-08-31 07:29 UTC, TapishKhari commented
I have added the Formspree in the form action.

2022-08-31 07:44 UTC, prolajumokeoni approved these changes
Hi @TapishKhari 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-31 07:46 UTC, merged